# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11af6e7e3c1a7488a88d632dbad997936156e52c1cf7b2d0c832a3636e7c64c73e5c73f373aea561ae44f5a0231b79e5ca633943e34355d5dd8f31cc14053883

test:
  secret_key_base: 775be94a92cbcc8bdefd6863004a2bfc137ef69f9cb7deddc8d0b7de53be7ede6f8ffb4ee56fcd9cf1fd2612b099eb0649d7eb6326c680405c9eb6ba33c8336f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
